CREATE TABLE [dbo].[briefing]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[variant_no] [int] NULL,
[briefing_no] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proj_title] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[int_ref] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[delivery_date] [datetime] NULL,
[creation_date] [datetime] NULL,
[proj_action] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[document_msds_yn] [bit] NULL,
[document_spec_yn] [bit] NULL,
[document_lol_yn] [bit] NULL,
[document_odor_yn] [bit] NULL,
[document_fra_disclo_yn] [bit] NULL,
[document_fra_comp_yn] [bit] NULL,
[document_sh_cert_yn] [bit] NULL,
[document_mat_list_yn] [bit] NULL,
[document_ifra_yn] [bit] NULL,
[document_cert_yn] [bit] NULL,
[document_wt_loss] [bit] NULL,
[document_malodor_yn] [bit] NULL,
[document_cost_sheet_yn] [bit] NULL,
[document_frag_lev_yn] [bit] NULL,
[document_gc_analy_yn] [bit] NULL CONSTRAINT [DF_briefing_document_gc_analy_yn] DEFAULT ((1)),
[document_stab_yn] [bit] NULL,
[document_saf_eval] [bit] NULL,
[document_tosca] [bit] NULL,
[dialyn] [bit] NULL,
[bus_id] [int] NULL,
[sbu_id] [int] NULL,
[cur_id] [int] NULL,
[pro_id] [int] NULL,
[str_id] [int] NULL,
[samp_comment] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[samp_delivery] [int] NULL,
[addional_inf_yn] [bit] NULL,
[mark_concept] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bench_comp] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tgt_group] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spec_claims] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[no_eval_level] [int] NULL,
[deadline] [datetime] NULL,
[comm_deadl] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[no_prod_form] [int] NULL,
[frag_desc] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[no_price_level] [int] NULL,
[no_subm] [int] NULL,
[no_concepts] [int] NULL,
[no_total_subm] [int] NULL,
[agree_yn] [bit] NULL,
[agree_perc] [int] NULL,
[test_stab_crt] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[del_unfr_bulk] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comment] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brf_id_variant] [int] NULL,
[eval_type_1] [int] NULL,
[eval_type_2] [int] NULL,
[eval_type_3] [int] NULL,
[eval_type_4] [int] NULL,
[sta_id] [int] NULL,
[status_since_date] [datetime] NULL,
[status_changed_by] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[perfume_no_samples] [int] NULL,
[perfume_weight] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[perfume_adr_id] [int] NULL,
[created_by] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[approved_frag] [bit] NULL,
[lit_id] [int] NULL,
[final_deadline] [datetime] NULL,
[comm_final_deadl] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reopen_yn] [bit] NULL,
[lgo_id] [int] NULL,
[fragrance_names] [nvarchar] (3000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name_of_current_perfume] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[briefing] ADD CONSTRAINT [PK_briefing] PRIMARY KEY CLUSTERED  ([id]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[briefing] ADD CONSTRAINT [FK_briefing_geographical_scope] FOREIGN KEY ([lgo_id]) REFERENCES [dbo].[geographical_scope] ([id])
GO
ALTER TABLE [dbo].[briefing] ADD CONSTRAINT [FK_briefing_local_incoterm] FOREIGN KEY ([lit_id]) REFERENCES [dbo].[local_incoterm] ([id])
GO
